name: 部署
on: 
    push:
        branches:
            - master
    workflow_dispatch:
jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - run: npm install
            - run: npm run docs:build
            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v2
              with: 
                  path: docs/.vitepress/dist
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: docs/.vitepress/dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Generate knownHost
              run: ssh-keyscan gitee.com > giteeKnownHosts
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: git@gitee.com:musicfree/MusicFree.git
                BRANCH: gh-pages
                FOLDER: docs/.vitepress/dist
                SSH_PRIVATE_KEY: ${{ secrets.GITEE_DEPLOY_PRIVATE_KEY }}
                KNOWN_HOSTS_FILE: giteeKnownHosts
            - name: Build Gitee Pages
              uses: yanglbme/gitee-pages-action@main
              with:
              gitee-username: maotoumao
              gitee-password: ${{ secrets.GITEE_PASSWORD }}
              gitee-repo: musicfree/MusicFree
              branch: gh-pages
                
            
            
